DROP TABLE IF EXISTS NOBEL_WIN;
CREATE TABLE IF NOT EXISTS NOBEL_WIN (
   YEAR INTERGER,
   SUBJECT TEXT,
   WINNER TEXT,
   COUNTRY TEXT,
   CATEGORY TEXT

);

INSERT INTO NOBEL_WIN (YEAR, SUBJECT, WINNER, COUNTRY, CATEGORY) VALUES
("1970", "PHYSICS", "HANNES ALFEN", "SWEDEN", "SCIENTIST"),
("1970", "PHYSICS", "LOUIS NEEL", "FRANCE", "SCIENTIST"),
("1971", "PHYSICS", "PAUL", "FRANCE", "SCIENTIST"),
("1971", "CHEMISTRY", "HAMILTON", "SWEDEN", "LINGUIST"),
("1972", "LITREATURE", "BENARD KELSON", "GERMANY", "ECONOMIST"),
("1973", "ECONOMY", "JOSEPH", "RUSSIA", "ECONOMIST");

SELECT *
FROM NOBEL_WIN
WHERE SUBJECT NOT LIKE 'P%';