CREATE TABLE IF NOT EXISTS PRODUCT(
    PRO_ID TEXT PRIMARY KEY ,
    PRO_NAME TEXT,
    PRO_PRICE TEXT,
    PRO_COM TEXT

);

INSERT INTO PRODUCT(PRO_ID,PRO_NAME,PRO_PRICE,PRO_COM)VALUES
("101","MOTHERBOARD","3200","15"),
("102","KEYBOARD","450","16"),
("103","ZIP DRIVE","250","14");
SELECT PRO_NAME,PRO_PRICE
       FROM PRODUCT
       WHERE PRO_PRICE =
       (SELECT MIN (pro_price) FROM PRODUCT); 
